- name: "Firefox: Ensure profile directories exist"
  file:
    path: "{{ firefox_profile_dir }}"
    mode: "0774"
    owner: "{{ ansible_user }}"
    group: "wheel"
    state: "directory"

- name: "Firefox: Find all files and directories in source directory"
  find:
    path: "{{ ONESETUP_DIR }}/roles/firefox/files"
    file_type: any
  register: found_items

- name: "Firefox: Remove matching files from Firefox Profile Directory"
  file:
    path: "{{ firefox_profile_dir }}/{{ item.path | basename }}"
    state: absent
  loop: "{{ found_items.files }}"
  when: item.path | basename != ''  # Ensure we have a valid filename

- name: "Firefox: Create symlinks to {{ firefox_profile_dir }}"
  file:
    src: "{{ item.path }}"
    dest: "{{ firefox_profile_dir }}/{{ item.path | basename }}"
    state: link
  loop: "{{ found_items.files }}"
  when: item.path | basename != ''

