[BROWSER]

# Only Gecko-based browsers are supported (firefox, firefox-dev, waterfox, zen, ...)
type = "gecko" 

# Path to the Firefox profile's data storage 
# (about:profiles -> Root Directory -> absolute path)
path = "~/nas/storage/firefox/"

# >> MODULE TO FILE MAPPINGS <<
[MAPPINGS]
  # general settings (default browser, tabs, windows)
  general = [
    "prefs.js",
    "compatibility.ini",
    "times.json",
    "security_state",
    "sessionCheckpoints.json",
    "handlers.json"
  ]
  # Language settings (check spelling, language preference)
  language = [
    "prefs.js"
  ]
  # Basic design (fonts, tab bar, pill buttons, etc.)
  appearance = [
    "xulstore.json",
    "prefs.js",
    "icons/",
    "chrome/"
  # Custom CSS (userChrome.css stylings)
  css = [
    "chrome/" # if userChrome.css or userContent.css exists
  ]
  # Internal password manager (consider alternatives like Bitwarden, KeepassXC, etc.)
  credentials = [
    "logins.json",
    "logins-backup.json",
    "key4.db",
    "signedInUser.json"
  ]
  # Add-ons and their settings (installed from Mozilla’s add-ons site)
  extensions = [
    "extensions/",
    "addons.json",
    "extension-settings.json",
    "extension-preferences.json",
    "extension-store",
    "addonStartup.json.lz4"
  ]
  # Browsing data (cookies, history, active sessions)
  data = [
    "cookies.sqlite",
    "cookies.sqlite-wal",
    "places.sqlite",
    "places.sqlite-wal",
    "formhistory.sqlite",
    "favicons.sqlite",
    "favicons.sqlite-wal",
    "storage/",
    "storage-sync-v2.sqlite",
    "sessionstore.jsonlz4",
    "sessionstore-backups/",
    "permissions.sqlite",
    "serviceworker.txt",
    "notificationstore.json",
    "containers.json"
  ]
  # they are c
  keymaps = [
    "zen-keyboard-shortcuts.json"
  ],
  # bookmarks... these comments are so useless, thanks for reading them tho <3
  bookmarks = [
    "places.sqlite",
    "bookmarkbackups/"
  ]
  # miscellaneous (certificates, permissions, http security)
  miscellaneous = [
    "cert9.db",
    "permissions.sqlite",
    "SiteSecurityServiceState.bin",
    "AlternateServices.bin",
    "webappsstore.sqlite"
  ]

