# Default config.yml consumed by onesetup.
# Expected Location: $XDG_CONFIG_HOME/onesetup/config.yml or $HOME/.config/onesetup/config.yml
# Can't use environment variables here but ~/ can be used & reffers to $HOME/
---
remote:
  provider: "github" # Default: github
  username: "onexbash" # Default: onexbash
  connection: "https" # Default: https
  project_repo: "onesetup" # Default: onesetup
  dotfiles_repo: "dotfiles" # Default: dotfiles
system:
  os: "" # Default: Auto-Detected by detect_os() function in ./scripts/util.sh
  username: "" # Default: Value from Environment Variable "$USER"
  root_user: "" # Default: Value from Command "id -nu 0"
  user_group: "" # Default: Value from Command "id -ng"
  admin_group: "" # Default: Value from Command "id -ng 0"
  config_dir: "" # Default: $XDG_CONFIG_HOME/onesetup or $HOME/.config/onesetup
  storage_dir: "" # Default: $XDG_STATE_HOME/onesetup or $HOME/.local/state/onesetup
  dotfiles_dir: "" # Default: $XDG_DATA_HOME/dotfiles or $HOME/.local/share/dotfiles
  bin_dir: "/usr/local/bin" # Default: /usr/local/bin
  tmp_dir: "/tmp" # Default: /tmp

project:
  debug: 0 # Default: 0
