version: "3.8"
services:
  onesetup:
    image: onesetup
    container_name: onesetup
    hostname: onesetup
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
      - "7000:7000"
      - "22:22"
    tty: true
    stdin_open: true
    environment:
      - HOME=/home/onesetup
      - XDG_CONFIG_HOME=${HOME}/.config
      - ZDOTDIR=${XDG_CONFIG_HOME}/zsh
networks:
  onesetup:
    name: "onesetup"
