version: "3.8"
services:
  onesetup-controller:
    image: onesetup-controller
    container_name: onesetup-controller
    hostname: onesetup-controller
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/opt/onesetup
    working_dir: /opt/onesetup
