version: "3.8"
services:
  onesetup:
    image: onesetup
    container_name: onesetup
    hostname: onesetup
    build:
      context: ${ONESETUP_DIR}
      dockerfile: ./Dockerfile
      args:
        - ONESETUP_DIR=${ONESETUP_DIR}
        - ONESETUP_REPO=${ONESETUP_REPO}
        - DOTFILES_DIR=${DOTFILES_DIR}
        - DOTFILES_REPO=${DOTFILES_REPO}
    volumes:
      # Mount installation directory
      - ${ONESETUP_DIR}:/home/onesetup/src
    ports:
      - "8000:8000"
      - "7000:7000"
      - "22:22"
    # Use environment variables from entrypoint script (build-time) to set container environment (runtime)
    environment:
      - ONESETUP_DIR=${ONESETUP_DIR}
      - ONESETUP_REPO=${ONESETUP_REPO}
      - DOTFILES_DIR=${DOTFILES_DIR}
      - DOTFILES_REPO=${DOTFILES_REPO}
      - ANSIBLE_DEBUG=1
    tty: true
    stdin_open: true
networks:
  onesetup:
    name: "onesetup"
