version: "3.8"
services:
  onesetup-controller:
    container_name: onesetup-controller
    hostname: onesetup-controller
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
