version: "3.8"
services:
  onesetup:
    image: onesetup
    container_name: onesetup
    hostname: onesetup
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - "ONESETUP_DIR:${ONESETUP_DIR}"
        - "ONESETUP_REPO_NAME:${ONESETUP_REPO_NAME}"
    volumes:
      # Mount current directory
      - .:/home/onesetup/src
    ports:
      - "8000:8000"
      - "7000:7000"
      - "22:22"
    environment:
      - "ONESETUP_DIR:${ONESETUP_DIR}"
      - "ONESETUP_REPO_NAME:${ONESETUP_REPO_NAME}"
    tty: true
    stdin_open: true
networks:
  onesetup:
    name: "onesetup"
