version: "3.8"
services:
  onesetup-controller:
    image: onesetup-controller
    container_name: onesetup-controller
    hostname: onesetup-controller
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
      - "22:22"
    tty: true
    stdin_open: true
    # working_dir: /opt/onesetup
networks:
  - "onesetup"
network_mode: "host"
