version: "3.8"
services:
  onesetup:
    image: onesetup
    container_name: onesetup
    hostname: onesetup
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
      - "7000:7000"
      - "22:22"
    tty: true
    stdin_open: true
networks:
  onesetup:
    name: "onesetup"
