# -- -- -- -- -- -- -- -- #
# --     INVENTORY     -- #
# -- -- -- -- -- -- -- -- #

# -- WORKSTATIONS -- #
# variables
[workstation.vars]
ansible_port = 7000
ansible_user = "fschlegelone"
# hosts
[workstation.hosts]
onexmac = { ansible_host = "10.22.22.100" }
