# -- -- -- -- -- -- -- -- #
# --     INVENTORY     -- #
# -- -- -- -- -- -- -- -- #

# -- DEFAULT: variables -- #
# note: per host variables are set in host_vars/<hostname>.yml
[all.vars]
ansible_connection = "ssh"
ansible_port = 22

# -- WORKSTATION -- #
# hosts
[workstation.hosts]
onexmac-cratos = { ansible_host = "100.65.55.179" }
