# -- -- -- -- -- -- -- -- #
# --     INVENTORY     -- #
# -- -- -- -- -- -- -- -- #

# -- WORKSTATIONS -- #
# variables
[workstation.vars]
ansible_port = 22
# hosts
[workstation.hosts]
onexmac-cratos = { ansible_host = "100.65.55.179", ansible_user = "fschlegelone" }
