# -- -- -- -- -- -- -- -- #
# --     INVENTORY     -- #
# -- -- -- -- -- -- -- -- #

# -- WORKSTATION -- #
# variables
[workstation.vars]
ansible_user = "{{ sudo_user }}"                # set in host_vars/<hostname>.yml
ansible_become_password = "{{ sudo_password }}" # set in host_vars/<hostname>.yml
ansible_password = "{{ sudo_password }}"        # set in host_vars/<hostname>.yml
ansible_port = 22
# hosts
[workstation.hosts]
onexmac-cratos = { ansible_host = "100.65.55.179" }
