[all]
localhost ansible_connection=local

[wsl]
localhost ansible_connection=local

[windows]
win11 ansible_host=onexwin
      ansible_connection=winrm
      ansible_winrm_transport=basic
      ansible_winrm_server_cert_validation=ignore
      ansible_port=5985
      ansible_user=onexbash
      ansible_password="{{ SUDO_PASSWORD }}"
[windows:vars]
ansible_become_method=runas
ansible_become_user=SYSTEM
