---
- name: "onesetup - Remote Target Playbook"
  hosts:
    - workstation
  connection: ssh
  gather_facts: true
  # -- Variables -- #
  vars:
    # ansible variables
    ansible_become_password: "{{ sudo_password }}"
    ansible_password: "{{ sudo_password }}"
    ansible_facts_parallel: true # allow parallel facts gathering
    # environment variables
    HOME: "{{ ansible_env.HOME }}"
    XDG_CONFIG_HOME: "{{ HOME }}/.config"
    ZDOTDIR: "{{ XDG_CONFIG_HOME }}/zsh"
    # onesetup variables (passed by control-node entrypoint script)
    ONESETUP_DIR: '{{ lookup("env", "ONESETUP_DIR") }}'
    DOTFILES_DIR: '{{ lookup("env", "DOTFILES_DIR") }}'
    ONESETUP_REPO: '{{ lookup("env", "ONESETUP_REPO") }}'
    DOTFILES_REPO: '{{ lookup("env", "DOTFILES_REPO") }}'
    ONESETUP_REPO_SSH: "git@github.com:{{ ONESETUP_REPO }}.git"
    ONESETUP_REPO_HTTPS: "https://github.com/{{ ONESETUP_REPO }}.git"
    DOTFILES_REPO_SSH: "git@github.com:{{ DOTFILES_REPO }}.git"
    DOTFILES_REPO_HTTPS: "https://github.com/{{ DOTFILES_REPO }}.git"
  # -- Pre Tasks -- #
  pre_tasks:
    - name: 'Include Pre-Tasks'
      include_tasks: '{{ item }}'
      loop: "{{ lookup('ansible.builtin.fileglob', 'pre_tasks/*.yml', wantlist=True) }}"
      tags: ['always']
  # -- Tasks -- #
  tasks:
    # import tasks
    - import_tasks: tasks/dotfiles.yml
  #roles:
  #  - role: "firefox"
  #    tags: ["firefox"]
