---
# -- -- -- -- -- -- -- -- #
# --   MAIN PLAYBOOK   -- #
- name: "onesetup"
  # -- CONNECTION -- #
  hosts: localhost
  connection: local
  # -- VARIABLES -- #
  vars:
    ONESETUP_DIR: "{{ lookup('ansible.builtin.env', 'ONESETUP_DIR') }}"
    ONESETUP_REPO: "{{ lookup('ansible.builtin.env', 'ONESETUP_REPO') }}"
    DOTFILES_DIR: "{{ lookup('ansible.builtin.env', 'DOTFILES_DIR') }}"
    DOTFILES_REPO: "{{ lookup('ansible.builtin.env', 'DOTFILES_REPO') }}"
    DOTFILES_REPO_HTTPS: "https://github.com/{{ DOTFILES_REPO }}.git"
    DOTFILES_REPO_SSH: "git@github.com:{{ DOTFILES_REPO }}.git"
    USER: "{{ lookup('ansible.builtin.env', 'USER') }}"
    HOME: "{{ lookup('ansible.builtin.env', 'HOME') }}"
    XDG_CONFIG_HOME: "{{ lookup('ansible.builtin.env', 'XDG_CONFIG_HOME', default=HOME + '/.config/') }}"
    ZDOTDIR: "{{ lookup('ansible.builtin.env', 'ZDOTDIR') }}"
    CARGO_HOME: "{{ lookup('ansible.builtin.env', 'CARGO_HOME', default=HOME + '/.config/cargo') }}"
    os_task_map:
      Darwin: osx
      RedHat: fedora
      Windows: windows
  vars_files:
    - group_vars/default/ssh.yml
  pre_tasks:
    # -- INCLUDE PRE_TASKS -- #
    # Detect OS
    - name: "Detect Operating System"
      set_fact:
        onesetup_os: "{{ os_task_map[ansible_facts['os_family']] }}"
        # onesetup_os: "{{ os_task_map[ansible_facts['os_family']] | default(undef(hint='Unsupported OS: ' + ansible_facts['os_family'])) }}"
    # Run Default pre_tasks (for every OS)
    - name: "pre_tasks | Default"
      include_tasks: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/pre_tasks/default/*.yml"
    # Run OS-Specific pre_tasks
    - name: "pre_tasks | {{ onesetup_os }}"
      include_tasks: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/pre_tasks/{{ onesetup_os }}/*.yml"
    # -- INCLUDE GROUP_VARS -- #
    - name: "group_vars | Default"
      include_vars:
        dir: "group_vars/default"
        extensions:
          - yml
    - name: "group_vars | {{ onesetup_os }}"
      include_vars:
        dir: "group_vars/{{ onesetup_os }}"
        extensions:
          - yml
  # -- INCLUDE ROLES -- #
  roles:
    - { role: dotfiles, tags: ["dotfiles"] }
    # - { role: apps, tags: ["apps"] }
    # - { role: settings, tags: ["settings"] }
