---
# -- -- -- -- -- -- -- -- #
# --   MAIN PLAYBOOK   -- #
- name: onesetup
  
  # -- CONNECTION -- #
  hosts: localhost
  connection: local
  
  # -- VARIABLES -- #
  vars:
    # Environment Variables: Remote 
    ONESETUP_REMOTE_PROVIDER: "{{ ansible_facts['env']['ONESETUP_REMOTE_PROVIDER'] }}"
    ONESETUP_REMOTE_USERNAME: "{{ ansible_facts['env']['ONESETUP_REMOTE_USERNAME'] }}"
    ONESETUP_REMOTE_CONNECTION: "{{ ansible_facts['env']['ONESETUP_REMOTE_CONNECTION'] }}"
    ONESETUP_REMOTE_PROJECT_REPO: "{{ ansible_facts['env']['ONESETUP_REMOTE_PROJECT_REPO'] }}"
    ONESETUP_REMOTE_DOTFILES_REPO: "{{ ansible_facts['env']['ONESETUP_REMOTE_DOTFILES_REPO'] }}" 
    # Environment Variables: System
    ONESETUP_SYSTEM_OS: "{{ ansible_facts['env']['ONESETUP_SYSTEM_OS'] }}"
    ONESETUP_SYSTEM_USERNAME: "{{ ansible_facts['env']['ONESETUP_SYSTEM_USERNAME'] }}"
    ONESETUP_SYSTEM_ROOT_USER: "{{ ansible_facts['env']['ONESETUP_SYSTEM_ROOT_USER'] }}"
    ONESETUP_SYSTEM_CONFIG_DIR: "{{ ansible_facts['env']['ONESETUP_SYSTEM_CONFIG_DIR'] }}"
    ONESETUP_SYSTEM_INSTALL_DIR: "{{ ansible_facts['env']['ONESETUP_SYSTEM_INSTALL_DIR'] }}"
    ONESETUP_SYSTEM_STORAGE_DIR: "{{ ansible_facts['env']['ONESETUP_SYSTEM_STORAGE_DIR'] }}"
    ONESETUP_SYSTEM_DOTFILES_DIR: "{{ ansible_facts['env']['ONESETUP_SYSTEM_DOTFILES_DIR'] }}"
    ONESETUP_SYSTEM_BIN_DIR: "{{ ansible_facts['env']['ONESETUP_SYSTEM_BIN_DIR'] }}"
    ONESETUP_SYSTEM_TMP_DIR: "{{ ansible_facts['env']['ONESETUP_SYSTEM_TMP_DIR'] }}"
    ONESETUP_SYSTEM_USER_GROUP: "{{ ansible_facts['env']['ONESETUP_SYSTEM_USER_GROUP'] }}"
    ONESETUP_SYSTEM_ADMIN_GROUP: "{{ ansible_facts['env']['ONESETUP_SYSTEM_ADMIN_GROUP'] }}"
    # Environment Variables: Project
    ONESETUP_PROJECT_DEVELOPMENT: "{{ ansible_facts['env']['ONESETUP_PROJECT_DEVELOPMENT'] }}"
    ONESETUP_PROJECT_ANSIBLE_DEBUG: "{{ ansible_facts['env']['ONESETUP_PROJECT_ANSIBLE_DEBUG'] }}"
    ONESETUP_PROJECT_SCRIPT_DEBUG: "{{ ansible_facts['env']['ONESETUP_PROJECT_SCRIPT_DEBUG'] }}"
    # Environment Variables: Dynamic
    ONESETUP_PROJECT_REPO_URI: "{{ ansible_facts['env']['ONESETUP_PROJECT_REPO_URI'] }}"
    ONESETUP_DOTFILES_REPO_URI: "{{ ansible_facts['env']['ONESETUP_DOTFILES_REPO_URI'] }}"
    ONESETUP_PROJECT_REPO_RAW: "{{ ansible_facts['env']['ONESETUP_PROJECT_REPO_RAW'] }}"
    ONESETUP_DOTFILES_REPO_RAW: "{{ ansible_facts['env']['ONESETUP_DOTFILES_REPO_RAW'] }}"
    ONESETUP_DIR_DEV: "{{ ansible_facts['env']['ONESETUP_DIR_DEV'] }}"
    # Environment Variables: User Environment
    USER: "{{ ansible_facts['env']['USER'] }}"
    HOME: "{{ ansible_facts['env']['HOME'] }}"
    XDG_CONFIG_HOME: "{{ ansible_facts['env']['XDG_CONFIG_HOME'] }}"
    ZDOTDIR: "{{ ansible_facts['env']['ZDOTDIR'] }}"
    CARGO_HOME: "{{ ansible_facts['env']['CARGO_HOME'] }}"
  # Variable Prompts
  vars_prompt:
    - name: SUDO_PASSWORD
      prompt: "Sudo password"
      private: true

  # -- PRE-TASKS -- #
  pre_tasks:
    # Set Become Password
    - name: "auth | set become password gathered in user-prompt"
      set_fact:
        ansible_become_password: "{{ SUDO_PASSWORD }}"
        cacheable: false
      no_log: true
    # Include pre_task for System Discovery
    - name: "pre_tasks | System Discovery"
      ansible.builtin.include_tasks: "{{ playbook_dir }}/pre_tasks/all/system_discovery.yml"
    # Include OS-Independent pre_tasks (for every OS)
    - name: "pre_tasks | OS-Independent (all)"
      ansible.builtin.include_tasks: "{{ item_pretask }}"
      with_fileglob:
        - "{{ playbook_dir }}/pre_tasks/all/*.yml"
      loop_control:
        loop_var: item_pretask
    # Include OS-Specific pre_tasks
    - name: "pre_tasks | OS-Specific ({{ onesetup_os }})"
      ansible.builtin.include_tasks: "{{ item_pretask }}"
      with_fileglob:
        - "{{ playbook_dir }}/pre_tasks/{{ onesetup_os }}/*.yml"
      loop_control:
        loop_var: item_pretask
    # Include OS-Specific Variables
    - name: "group_vars | Include OS-specific variables ({{ onesetup_os }})"
      ansible.builtin.include_vars:
        dir: "{{ playbook_dir }}/group_vars/{{ onesetup_os }}"
        extensions:
          - yml
      ignore_errors: true # Skip if OS-specific folder doesnt exist
  
  # -- ROLES -- #
  roles:
    - { role: dotfiles, tags: ["dotfiles"] }
    - { role: apps, tags: ["apps"] }
    - { role: settings, tags: ["settings"] }
