---
- name: "onesetup - Controller Playbook"
  hosts:
    - localhost
  connection: local
  gather_facts: true
  tasks:
    - name: "Display System Info"
      setup:
        filter:
          - 'ansible_distribution'
          - 'ansible_machine_id'
          - 'ansible_*_mb'
