---
- name: "onesetup - Controller Playbook"
  hosts: localhost
  connection: local
  gather_facts: true
  # pre_tasks:
  #   - name: 'Include Pre-Tasks'
  #     include_tasks: '{{ item }}'
  #     loop: "{{ lookup('ansible.builtin.fileglob', 'pre_tasks/*.yml', wantlist=True) }}"
  #     tags: ['controller']
  tasks:
    - name: "Prepare SSH Directory"
      file:
        path: "~/.ssh"
        state: directory
        mode: "0700"
        recurse: false
    - name: "Decrypt & rollout onesetup ssh key (public)"
      copy:
        content: "{{ ssh_keys.onesetup_pub }}"
        dest: "~/.ssh/onesetup.pub"
        mode: "0644"
    - name: "Decrypt & rollout onesetup ssh key (private)"
      copy:
        content: "{{ ssh_keys.onesetup }}"
        dest: "~/.ssh/onesetup"
        mode: "0600"
    - name: "Add remote targets SSH fingerprint to known_hosts"
      known_hosts:
        path: ~/.ssh/known_hosts
        name: "{{ inventory_hostname }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -H ' + inventory_hostname) }}"

