---
- name: "onesetup - Controller Playbook"
  hosts:
    - localhost
  connection: local
  gather_facts: true
  tasks:
    - name: "Prepare SSH Directory"
      file:
        path: "/home/onesetup/.ssh"
        state: directory
        mode: "0700"
        owner: "onesetup"
        group: "wheel"
        recurse: false
    - name: "Decrypt & rollout onesetup ssh key (public)"
      copy:
        content: "{{ ssh_keys.id_onesetup_pub }}"
        dest: "/home/onesetup/.ssh/id_onesetup.pub"
        mode: "0644"
        owner: "onesetup"
        group: "wheel"
    - name: "Decrypt & rollout onesetup ssh key (private)"
      copy:
        content: "{{ ssh_keys.id_onesetup }}"
        dest: "/home/onesetup/.ssh/id_onesetup"
        mode: "0600"
        owner: "onesetup"
        group: "wheel"
