---
- name: "onesetup - Remote Target Playbook"
  hosts:
    - workstation
  connection: ssh
  gather_facts: true
  vars:
    ansible_become_password: "{{ sudo_password }}"
    ansible_password: "{{ sudo_password }}"
  environment:
    HOME: "{{ ansible_env.HOME }}"
    XDG_CONFIG_HOME: "{{ ansible_env.HOME }}/.config"
    XDG_DATA_HOME: "{{ ansible_env.HOME }}/.local/share"
    XDG_STATE_HOME: "{{ ansible_env.HOME }}/.local/state"
    XDG_CACHE_HOME: "{{ ansible_env.HOME }}/.cache"
    ZDOTDIR: "{{ ansible_env.HOME }}/.config/zsh"
    USER: "{{ ansible_env.USER }}"
    ONESETUP_DIR: "/opt/onesetup"
    ONESETUP_REPO_SSH: "git@github.com:onexbash/onesetup.git"
    ONESETUP_REPO_HTTPS: "https://github.com/onexbash/onesetup.git"
    DOTFILES_DIR: "/opt/dotfiles"
    DOTFILES_REPO_SSH: "git@github.com:onexbash/dotfiles.git"
    DOTFILES_REPO_HTTPS: "https://github.com/onexbash/dotfiles.git"
  pre_tasks:
    - name: 'Include Pre-Tasks'
      include_tasks: '{{ item }}'
      loop: "{{ lookup('ansible.builtin.fileglob', 'pre_tasks/*.yml', wantlist=True) }}"
      tags: ['always']
  tasks:
    - import_tasks: tasks/dotfiles.yml
