---
controller:
  hosts:
    controller:
      ansible_host: localhost
      ansible_connection: local
      ansible_user: "{{ host_user }}"
      ansible_ssh_private_key_file: "/opt/onesetup/ssh/onesetup" # path to the ssh key on the control node
macos:
  hosts:
    onexmac:
      ansible_host: 10.22.22.100
      ansible_user: "{{ host_user }}"
      ansible_ssh_private_key_file: "/opt/onesetup/ssh/onesetup" # path to the ssh key on the control node
