---
# Clone Dotfiles Repository
- name: 'Clone Dotfiles Repository'
  git:
    repo: '{{ DOTFILES_REPO_HTTPS }}'
    clone: true
    dest: '{{ DOTFILES_DIR }}'
    force: false # respect local changes to prevent dotfile loss
    remote: origin
    update: true
    recursive: true # whether submodules should be included/skipped

# File Permissions: Dotfiles
- name: 'Set File Permissions: {{ DOTFILES_DIR }}/*'
  file:
    path: '{{ DOTFILES_DIR }}'
    state: directory
    mode: '0774'
    owner: '{{ ansible_user }}'
    group: 'wheel'
    recurse: true

# Cleanup: global shell config
- name: 'Cleanup: global shell config files (bash & zsh)'
  file:
    path: '{{ item.dest }}'
    state: absent
  loop:
    - { src: "{{ DOTFILES_DIR }}/shell/global/profile", dest: "/etc/profile" }
    - { src: "{{ DOTFILES_DIR }}/shell/global/zshenv", dest: "/etc/zshenv" }
    - { src: "{{ DOTFILES_DIR }}/shell/global/zprofile", dest: "/etc/zprofile" }
    - { src: "{{ DOTFILES_DIR }}/shell/global/zshrc", dest: "/etc/zshrc" }
    - { src: "{{ DOTFILES_DIR }}/shell/global/zlogout", dest: "/etc/zlogout" }
  ignore_errors: true

# Rollout: global shell config
- name: "Rollout: global shell config files (bash & zsh)"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: '{{ ansible_user }}'
    group: "wheel"
    mode: "0644"
  loop:
    - { src: "{{ DOTFILES_DIR }}/shell/global/profile", dest: "/etc/profile" }
    - { src: "{{ DOTFILES_DIR }}/shell/global/zshenv", dest: "/etc/zshenv" }
    - { src: "{{ DOTFILES_DIR }}/shell/global/zprofile", dest: "/etc/zprofile" }
    - { src: "{{ DOTFILES_DIR }}/shell/global/zshrc", dest: "/etc/zshrc" }
    - { src: "{{ DOTFILES_DIR }}/shell/global/zlogout", dest: "/etc/zlogout" }

# Cleanup: Dotfiles Targets
- name: 'Clean up Dotfiles Targets'
  file:
    path: '{{ item.dest }}'
    state: absent
  loop:
    - { src: "{{ DOTFILES_DIR }}/shell/home", dest: "{{ XDG_CONFIG_HOME }}/zsh" }
    - { src: "{{ DOTFILES_DIR }}/nvim", dest: "{{ XDG_CONFIG_HOME }}/nvim" }
    - { src: "{{ DOTFILES_DIR }}/alacritty", dest: "{{ XDG_CONFIG_HOME }}/alacritty" }
    - { src: "{{ DOTFILES_DIR }}/git", dest: "{{ XDG_CONFIG_HOME }}/git" }
    - { src: "{{ DOTFILES_DIR }}/starship", dest: "{{ XDG_CONFIG_HOME }}/starship" }
    - { src: "{{ DOTFILES_DIR }}/aerospace", dest: "{{ XDG_CONFIG_HOME }}/aerospace" }
    - { src: "{{ DOTFILES_DIR }}/atuin", dest: "{{ XDG_CONFIG_HOME }}/atuin" }
    - { src: "{{ DOTFILES_DIR }}/eza", dest: "{{ XDG_CONFIG_HOME }}/eza" }
    - { src: "{{ DOTFILES_DIR }}/lazygit", dest: "{{ XDG_CONFIG_HOME }}/lazygit" }
    - { src: "{{ DOTFILES_DIR }}/zed", dest: "{{ XDG_CONFIG_HOME }}/zed" }
  ignore_errors: true

# Rollout: Dotfiles
- name: 'Symlink Dotfiles'
  file:
    src: '{{ item.origin }}'
    dest: '{{ item.target }}'
    state: link
    owner: '{{ ansible_user }}'
    group: "wheel"
    force: true
  loop:
    - { src: "{{ DOTFILES_DIR }}/shell/home", dest: "{{ XDG_CONFIG_HOME }}/zsh" }
    - { src: "{{ DOTFILES_DIR }}/nvim", dest: "{{ XDG_CONFIG_HOME }}/nvim" }
    - { src: "{{ DOTFILES_DIR }}/alacritty", dest: "{{ XDG_CONFIG_HOME }}/alacritty" }
    - { src: "{{ DOTFILES_DIR }}/git", dest: "{{ XDG_CONFIG_HOME }}/git" }
    - { src: "{{ DOTFILES_DIR }}/starship", dest: "{{ XDG_CONFIG_HOME }}/starship" }
    - { src: "{{ DOTFILES_DIR }}/aerospace", dest: "{{ XDG_CONFIG_HOME }}/aerospace" }
    - { src: "{{ DOTFILES_DIR }}/atuin", dest: "{{ XDG_CONFIG_HOME }}/atuin" }
    - { src: "{{ DOTFILES_DIR }}/eza", dest: "{{ XDG_CONFIG_HOME }}/eza" }
    - { src: "{{ DOTFILES_DIR }}/lazygit", dest: "{{ XDG_CONFIG_HOME }}/lazygit" }
    - { src: "{{ DOTFILES_DIR }}/zed", dest: "{{ XDG_CONFIG_HOME }}/zed" }
