---
# Ensure Dotfiles Directory Exists
- name: 'Ensure Dotfiles Directory Exists'
  file:
    path: '{{ dotfiles_dir }}'
    state: directory
    mode: '0755'

# Clone Dotfiles Repository
- name: 'Clone Dotfiles Repository'
  git:
    repo: '{{ dotfiles_repo_uri }}'
    dest: '{{ dotfiles_dir }}'
    update: true

# Cleanup Dotfiles Targets
- name: 'Clean up Dotfiles Targets'
  file:
    path: '{{ item.target }}'
    state: absent
  loop: '{{ dotfile_mapping }}'
  ignore_errors: true

# Symlink Dotfiles
- name: 'Symlink Dotfiles'
  file:
    src: '{{ item.origin }}'
    dest: '{{ item.target }}'
    state: link
    force: yes
  loop: '{{ dotfile_mapping }}'
