---

# Clone Dotfiles Repository
- name: 'Clone Dotfiles Repository'
  git:
    repo: '{{ dotfiles_repo_uri }}'
    dest: '{{ dotfiles_dir }}'
    update: true

# File Permissions: Dotfiles
- name: 'Set File Permissions: {{ dotfiles_dir }}/*'
  file:
    path: '{{ dotfiles_dir }}'
    state: directory
    mode: '0644'
    owner: '{{ ansible_user }}'
    group: '{{ sudo_group }}'
    recurse: true

# File Permissions: Dotfiles Directory
- name: 'Set File Permissions: {{ dotfiles_dir }}'
  file:
    path: '{{ dotfiles_dir }}'
    state: directory
    mode: '0755'
    owner: '{{ ansible_user }}'
    group: '{{ sudo_group }}'
    recurse: false

# Cleanup Dotfiles Targets
- name: 'Clean up Dotfiles Targets'
  file:
    path: '{{ item.target }}'
    state: absent
  loop: '{{ dotfile_mapping }}'
  ignore_errors: true

# Symlink Dotfiles
- name: 'Symlink Dotfiles'
  file:
    src: '{{ item.origin }}'
    dest: '{{ item.target }}'
    state: link
    force: true
  loop: '{{ dotfile_mapping }}'
