# -- -- -- -- -- -- -- --  -- #
# -- MACOS SYSTEM SETTINGS -- #
# -- -- -- -- -- -- -- --  -- #

# -- DOCK -- #
- name: Configure macOS Dock settings
  community.general.osx_defaults:
    domain: com.apple.dock
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  loop:
    # dock: position
    - { key: "orientation", type: "string", value: "bottom" }
    # dock: icon size
    - { key: "tilesize", type: "int", value: 36 }
    # dock: autohide
    - { key: "autohide", type: "bool", value: true }
    # dock: autohide animation time
    - { key: "autohide-time-modifier", type: "float", value: 0.2 }
    # dock: autohide delay
    - { key: "autohide-delay", type: "float", value: 0.1 }
    # dock: show-recents
    - { key: "show-recents", type: "bool", value: false }
    # dock: minimize effect
    - { key: "mineffect", type: "string", value: "scale" }
    # dock: scroll to exposé
    - { key: "scroll-to-open", type: "bool", value: true }
  notify: Restart Dock
- name: "Restart Dock daemon"
  handlers:
    - name: Restart Dock
      ansible.builtin.command: killall Dock
