---
# Clone Dotfiles Repository
- name: "Clone Dotfiles Repository"
  ansible.builtin.git:
    repo: "{{ DOTFILES_REPO_HTTPS }}"
    clone: true
    dest: "{{ DOTFILES_DIR }}"
    force: false # respect local changes to prevent dotfile loss
    remote: origin
    update: true
    recursive: true # whether submodules should be included/skipped
  become: true

# File Permissions: Global Shell Files
- name: "Set Permissions: Global Shell Files"
  ansible.builtin.file:
    path: "{{ item.src }}"
    state: "file"
    mode: "0644"
    owner: "root"
    group: "wheel"
    recurse: false
  loop: "{{ shell_global }}"
  become: true

# File Permissions: User Shell Files
- name: "Set Permissions: User Shell Files"
  ansible.builtin.file:
    path: "{{ item.src }}"
    state: "file"
    mode: "0644"
    owner: "{{ USER }}"
    group: "staff"
    recurse: false
  loop: "{{ shell_home }}"
  become: true

# File Permissions: ZSH Config Dir
- name: "Set Permissions: ZSH Config Dir"
  ansible.builtin.file:
    path: "{{ item.src }}"
    state: "directory"
    mode: "0744"
    owner: "{{ USER }}"
    group: "staff"
    recurse: true
  loop: "{{ zsh_config_dir }}"
  become: true

# Copy: Global Shell Files
- name: "Copy: Global Shell Files"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    owner: "root"
    group: "wheel"
    force: true
    remote_src: true
  loop: "{{ shell_global }}"
  become: true

# Cleanup: User Shell Files (dest)
- name: "Cleanup: User Shell Files"
  ansible.builtin.file:
    path: "{{ item.dest }}"
    state: "absent"
    force: true
  loop: "{{ shell_home }}"
  become: true

# Cleanup: ZSH Config Directory (dest)
- name: "Cleanup: ZSH Config Directory"
  ansible.builtin.file:
    path: "{{ item.dest }}"
    state: "absent"
    force: true
  loop: "{{ zsh_config_dir }}"
  become: true

# Cleanup: Dotfiles (dest)
- name: "Cleanup: Dotfiles"
  ansible.builtin.file:
    path: "{{ item.dest }}"
    state: "absent"
    force: true
  loop: "{{ dotfiles }}"
  ignore_errors: true
  become: true

# Symlink: User Shell Files
- name: "Symlink: User Shell Files"
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: "link"
    force: true
  loop: "{{ shell_home }}"

# Symlink: ZSH Config Directory
- name: "Symlink: Shell Config Directory"
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: "link"
    force: true
  loop: "{{ zsh_config_dir }}"

# Symlink: Dotfiles
- name: "Symlink: Dotfiles"
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: "link"
    force: true
  loop: "{{ dotfiles }}"
  ignore_errors: true
