---
# Casks
brew_casks:
  - alt-tab # Alt-Tab replacement
  - appcleaner # App Uninstaller
  - cleanshot # screenshot tool (paid)
  - deepl
  - discord
  - session # Onion routed messenger
  - tor-browser
  - firefox
  - firefox@developer-edition
  - gimp # Image Editor
  - git-credential-manager
  - keepassxc # File Based Password Manager
  - stirling-pdf # PDF Viewer (self hosted)
  - insomnia # API Client (like postman)
  - proton-drive # Proton Cloud Storage
  - proton-mail # Proton Mail Client
  - protonvpn # Proton VPN Client
  - proton-pass # Proton Password Manager
  - proton-meet # Proton Video Conference
  - proton-mail-bridge # Proton Bridge to allow Mail traffic over 3rd party E-Mail Clients
  - raycast # Smart Spotlight Replacement
  - spotify
  - utm # VM Management
  - sublime-text # Text Editor
  - canva
  - figma
  - obs # Streaming Software
  - keka # Compression Tool
  - kekaexternalhelper # Helper Utility for keka
  - whatsapp
  - karabiner-elements # Keyboard Mapping Tool

# Formulaes
brew_formulaes:
  # -- LANGUAGES -- #
  - typescript
  - ast-grep # structural code search tool
  - yazi # terminal file manager
  - go
  - proton-pass-cli
  - openjdk # java development kit
  - git-crypt # git repository file encryption
  - ruby
  - dotnet
  - composer # php composer
  - php # just there that mason.nvim throws no warning
  - sqlite
  - julia # just there that mason.nvim throws no warning
  - perl # just there that mason.nvim throws no warning
  - postgresql # database system
  - ansible # infrastructure as code
  - javacc # java parser
  - hashicorp/tap/terraform # infrastructure as code
  - bc # numeric processing language
  - lua
  - imagemagick
  - tree-sitter # exposes syntax tree used by LSPs
  # -- VERSION MANAGERS -- #
  - asdf # Version Manager for everything (extensible via plugins)
  - pyenv # python version manager
  - pyenv-virtualenv # python virtual environment manager
  # -- LINUX UTILITIES -- #
  - coreutils # gnu utilities
  - gnutls # gnu utilities
  - gawk # awk (gnu version)
  - git # git (gnu version)
  - gnu-sed # sed (gnu version)
  - gnu-tar # tar (gnu version)
  - gnupg # gpg (gnu version)
  - grep # grep (gnu version)
  - iproute2mac # linux ip commands for macos (iproute2)
  # -- COMPILER, INTERPRETER, PARSER, LIBRARIES .. -- #
  - cmake
  - cmake-docs
  - gcc # C compiler
  - xz # compression tool
  - openssh # replace built-in | ssh
  - openssl@3 # replace built-in | ssl
  - jq # json parser
  - zlib # data-compression library required by python
  - libgit2 # C library of git core methods
  - ncurses # text-based UI library
  - maven # java build tool
  # -- SHELL -- #
  - bash # bash (brew version)
  - zsh # zsh (brew version)
  - powershell # microsoft powershell
  - azure-cli # cli for azure
  - zsh-autocomplete
  - zsh-fast-syntax-highlighting # better version of zsh-syntax-highlighting
  - zsh-autosuggestions
  # -- PACKAGE & VERSION MANAGER -- #
  - luarocks # lua package manager
  - poetry # python package manager
  - pnpm # node package manager
  - yarn # node package manager
  - sdkman-cli # java version manager
  # -- TOOLS -- #
  - scc # code cost analyzer
  - fnm # node version manager
  - clipboard # clipboard manager
  - exiftool # tool for exif metadata
  - cloudflared # cloudflare cli
  - git-filter-repo # git tool for rewriting git commit history
  - infisical # secret manager
  - fontforge # font patcher / editor
  - unzip # extraction tool
  - tlrc # CLI Cheatsheet Engine (based on tldr)
  - pinentry
  - git-delta # git pager
  - glow # markdown preview
  - ollama # toolchain for llama AI
  - vim
  - zip # archiving tool
  - gh # Github CLI
  - defaultbrowser # utility to set default browser
  - catimg # ascii image preview
  - cheat # cheatsheet engine
  - sketchybar # custom macos menubar
  - fontconfig # font configuration API
  - bat # better cat
  - ripgrep # better grep
  - fastfetch # system info
  - zellij # terminal multiplexer (tmux alternative)
  # - telnet # UI for TELNET protocol
  - netcat # network cli tool
  - zoxide # better cd
  - speedtest # Speedtest CLI (tap: `teamookla/speedtest`)
  - ffmpegthumbnailer # terminal video thumbnailer
  - mas # macos app store CLI interface
  - unar # unarchiving tool
  # - poppler # pdf rendering library
  - tree
  - wget
  - svgo # svg optimizer
  - starship
  - pastel # color cli tool
  - lazygit # git cli tool
  - borders # window borders
  - eza # better ls
  - fd # better find
  - fzf # fuzzy finder
  - kubectl # kubernetes cli
  - atuin # shell history tool
  - podman
  - podman-compose

# Taps
brew_taps:
  - asmvik/formulae # used by: yabai
  - FelixKratz/formulae # used by: SketchyBar, JankyBorders
  - hashicorp/tap # used by: terraform and other hashicorp software
  - nikitabobko/tap # used by: aerospace
  - sdkman/tap # used by: sdkman (development kit manager)
  - teamookla/speedtest # used by: speedtest-cli
