---
# Prefix
brew_prefix: "{{ '/opt/homebrew' if ansible_facts['architecture'] == 'arm64' else '/usr/local' }}"

# Casks
brew_casks:
  - aerospace # Tiling Window Manager with workspaces
  - capso # MacOS Screenshot Tool
  - claude-code # Claude-Code App & CLI Tool
  - shotcut # Video Editing
  - alt-tab # Alt-Tab replacement
  - appcleaner # App Uninstaller
  # - alacritty # Terminal Emulator (Cross Platform) # TODO: create local cask for installation because the official cask was disabled (cause the devs didnt want to use a paid apple developer account to sign it for gatekeeper)
  - wezterm # Terminal Emulator (Cross Platform)
  - kitty # Terminal Emulator (MacOS & Linux)
  - ghostty # Terminal Emulator (MacOS & Linux)
  - deepl
  - discord
  - session # Onion routed messenger
  - tor-browser
  - firefox@developer-edition
  - gimp # Image Editor
  #   - git-credential-manager # TODO: fails with err, check why
  - keepassxc # File Based Password Manager
  - stirling-pdf # PDF Viewer (self hosted)
  - insomnia # API Client (like postman)
  - proton-drive # Proton Cloud Storage
  - proton-mail # Proton Mail Client
  - protonvpn # Proton VPN Client
  - proton-pass # Proton Password Manager
  - proton-meet # Proton Video Conference
  - proton-mail-bridge # Proton Bridge to allow Mail traffic over 3rd party E-Mail Clients
  - raycast # Smart Spotlight Replacement
  - spotify
  - utm # VM Management
  - sublime-text # Text Editor
  - intellij-idea-oss # IntelliJ Community Edition (replacement when nvim gets on my nerves)
  - vscodium # VSCodium (replacement when nvim gets on my nerves)
  - zed # Interesting IDE Project written in rust
  - canva
  - figma
  - obs # Streaming Software
  - keka # Compression Tool
  - kekaexternalhelper # Helper Utility for keka
  - whatsapp
  - karabiner-elements # Keyboard Mapping Tool

# Formulas
brew_formulaes:
  # -- LANGUAGES -- #
  - ast-grep # structural code search tool
  - yazi # terminal file manager
  - proton-pass-cli
  - git-crypt # git repository file encryption
  - sqlite
  - ansible # infrastructure as code
  - hashicorp/tap/terraform # infrastructure as code
  - lua
  - imagemagick
  - libpq # PostgreSQL Client (without the full server & daemon that the 'postgres' formulae installs)
  # -- VERSION MANAGERS -- #
  - asdf # Version Manager for everything (extensible via plugins)
  # -- LINUX UTILITIES -- #
  - coreutils # gnu utilities
  - gawk # awk (gnu version)
  - git # git (gnu version)
  - gnu-sed # sed (gnu version)
  - gnu-tar # tar (gnu version)
  - gnupg # gpg (gnu version)
  - grep # grep (gnu version)
  - iproute2mac # Linux IP commands for MacOS (iproute2)
  # -- COMPILER, INTERPRETER, PARSER, LIBRARIES .. -- #
  - cmake
  - gcc # C compiler
  - xz # compression tool
  - openssh # replace built-in | ssh
  - openssl@3 # replace built-in | ssl
  - jq # json parser
  - maven # java build tool
  # -- SHELL -- #
  - bash # bash (brew version)
  - zsh # zsh (brew version)
  - powershell # Microsoft Powershell
  - azure-cli # CLI for Azure
  # -- PACKAGE & VERSION MANAGER -- #
  - luarocks # Lua package manager
  - poetry # python package manager
  - pnpm # node package manager
  - yarn # node package manager
  - sdkman-cli # java version manager
  # -- TOOLS -- #
  - scc # code cost analyzer
  - fnm # node version manager
  - clipboard # clipboard manager
  - exiftool # tool for exif metadata
  - cloudflared # cloudflare CLI
  - git-filter-repo # git tool for rewriting git commit history
  - infisical # secret manager
  - fontforge # font patcher / editor
  - unzip # extraction tool
  - tlrc # CLI Cheatsheet Engine (based on tldr)
  - pinentry
  - git-delta # git pager
  - glow # markdown preview
  - ollama # Toolchain for llama AI
  - vim
  - zip # archiving tool
  - gh # Github CLI
  - defaultbrowser # utility to set default browser
  - catimg # ASCII Image preview
  - sketchybar # custom MacOS Menubar
  - bat # better cat
  - ripgrep # better grep
  - fastfetch # system info
  - zellij # terminal multiplexer (tmux alternative)
  # - telnet # UI for TELNET protocol
  - netcat # network CLI tool
  - zoxide # better cd
  - speedtest # Speedtest CLI (tap: `teamookla/speedtest`)
  - ffmpegthumbnailer # terminal video thumbnailer
  - mas # MacOS app store CLI interface
  - unar # Unarchiving tool
  # - poppler # PDF rendering library
  - tree
  - tree-sitter-cli # Tree-Sitter CLI required for nvim-treesitter to work
  - wget
  - svgo # SVG optimizer
  - starship
  - pastel # color CLI tool
  - lazygit # git CLI tool
  - borders # window borders
  - eza # better ls
  - fd # better find
  - fzf # fuzzy finder
  - sk # fuzzy finder
  - kubectl # Kubernetes CLI
  - atuin # shell history tool
  - podman
  - podman-compose

# Taps
brew_taps:
  - FelixKratz/formulae # used by: SketchyBar, JankyBorders
  - hashicorp/tap # used by: Terraform and other Hashicorp software
  - nikitabobko/tap # used by: aerospace
  - sdkman/tap # used by: sdkman
  - teamookla/speedtest # used by: speedtest-cli
  - lzhgus/tap # used by: capso
