---
brew_taps:
  - azure/functions # azure functions core tools
  - powershell/tap # powershell
  - FelixKratz/formulae
  - koekeishiya/formulae # yabai & skhd
  - hashicorp/tap # terraform
  - sdkman/tap # java version manager
