---
dock_items:
  - name: "Ghostty"
    path: "/Applications/Ghostty.app"
  - name: "Firefox Developer Edition"
    path: "/Applications/Firefox Developer Edition.app"
  - name: "Proton Mail"
    path: "/Applications/Proton Mail.app"
  - name: "Spotify"
    path: "/Applications/Spotify.app"
  - name: "Sublime Text"
    path: "/Applications/Sublime Text.app"
  - name: "Zed"
    path: "/Applications/Zed.app"
  - name: "AppCleaner"
    path: "/Applications/AppCleaner.app"
  - name: "KeePassXC"
    path: "/Applications/KeePassXC.app"
  - name: "Claude"
    path: "/Applications/Claude.app"
