# -- TAPS -- #
- name: "tap repositories"
  community.general.homebrew_tap:
    name: "{{ item_tap }}"
    path: "/usr/local/bin:/opt/homebrew/bin"
    state: present
  loop: "{{ brew_taps }}"
  loop_control:
    loop_var: item_tap
  ignore_errors: true
  register: log_tap

# -- FORMULAES -- #
- name: "install formulaes"
  community.general.homebrew:
    name: "{{ item_formulae }}"
    path: "/usr/local/bin:/opt/homebrew/bin"
    state: latest
    force_formula: true # avoids conflicts where a package has both cask and formulae
    update_homebrew: false # should be disabled and handled in a pre_task
    upgrade_all: false # should be disabled and handled in a post_task
    install_options:
      - quiet # reduce output
  loop: "{{ brew_formulaes }}"
  loop_control:
    loop_var: item_formulae
  ignore_errors: true # failed tasks should not exit the playbook (to ensure that one broken package doesnt break everything)
  register: log_formulae # register output for debugging

# -- CASKS -- #
- name: "install casks"
  community.general.homebrew_cask:
    name: "{{ item_cask }}"
    path: "/usr/local/bin:/opt/homebrew/bin"
    state: latest
    accept_external_apps: true
    greedy: true
    install_options:
      # - no-quarantine # disable the macos quarantine option as it sometimes marks apps as damaged that are perfectly fine.
      - quiet # reduce output
    # sudo_password: "{{ ansible_become_password }}" # TODO: pass password gathered by user prompt
    update_homebrew: false # should be disabled(!) updates of the homebrew package manager itself are handled by a pre_task
    upgrade_all: false # should be disabled(!) upgrades of all brew packages are handled by a post_task (formulaes, casks & taps)
  loop: "{{ brew_casks }}"
  loop_control:
    loop_var: item_cask
  ignore_errors: true # failed tasks should not exit the playbook (to ensure that one broken package doesnt break everything)
  register: log_cask # register output for debugging
