---
shell_global:
  - { src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/shell/global/zshenv", dest: "/etc/zshenv" }
  - { src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/shell/global/zprofile", dest: "/etc/zprofile" }
  - { src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/shell/global/zshrc", dest: "/etc/zshrc" }
  - { src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/shell/global/zlogout", dest: "/etc/zlogout" }
  - { src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/shell/global/profile", dest: "/etc/profile" }
  - { src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/shell/global/bashrc", dest: "/etc/bashrc" }
  - {
      src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/shell/global/bash_profile",
      dest: "/etc/bash_profile",
    }
  - {
      src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/shell/global/bash_logout",
      dest: "/etc/bash_logout",
    }
  - { src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/shell/global/shells", dest: "/etc/shells" }

dotfiles:
  # aerospace
  - {
      src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/aerospace",
      dest: "{{ XDG_CONFIG_HOME }}/aerospace",
    }
  # atuin
  - { src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/atuin", dest: "{{ XDG_CONFIG_HOME }}/atuin" }
  # eza
  - { src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/eza", dest: "{{ XDG_CONFIG_HOME }}/eza" }
  # ghostty
  - { src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/ghostty", dest: "{{ XDG_CONFIG_HOME }}/ghostty" }
  # git
  - { src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/git", dest: "{{ XDG_CONFIG_HOME }}/git" }
  # lazygit
  - { src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/lazygit", dest: "{{ XDG_CONFIG_HOME }}/lazygit" }
  # nvim
  - { src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/nvim", dest: "{{ XDG_CONFIG_HOME }}/nvim" }
  - { src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/nvim_onevim", dest: "{{ XDG_CONFIG_HOME }}/nvim_onevim" }
  - { src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/nvim_astro", dest: "{{ XDG_CONFIG_HOME }}/nvim_astro" }
  # powershell
  - { src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/powershell", dest: "{{ XDG_CONFIG_HOME }}/powershell" }
  # karabiner
  - { src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/karabiner", dest: "{{ XDG_CONFIG_HOME }}/karabiner" }
  # homebrew
  - { src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/homebrew", dest: "{{ XDG_CONFIG_HOME }}/homebrew" }
  # shell
  - { src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/shell/home", dest: "{{ XDG_CONFIG_HOME }}/shell" }
  # starship
  - {
      src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/starship",
      dest: "{{ XDG_CONFIG_HOME }}/starship",
    }
  # vim
  - { src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/vim", dest: "{{ XDG_CONFIG_HOME }}/vim" }
  # zed
  - { src: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}/zed", dest: "{{ XDG_CONFIG_HOME }}/zed" }
