---
# Ensure LaunchAgents Directory exists
- name: "Ensure LaunchAgents Directory exists"
  ansible.builtin.file:
    path: "{{ HOME }}/Library/LaunchAgents"
    state: directory
    mode: "0755"
    owner: "{{ ONESETUP_SYSTEM_USERNAME }}"
    group: "{{ ONESETUP_SYSTEM_USER_GROUP }}"

# Rollout LaunchAgent for every app in {{ autostart_apps }}
- name: "Rollout LaunchAgent files"
  ansible.builtin.template:
    src: autostart.plist.j2
    dest: "{{ HOME }}/Library/LaunchAgents/{{ autostart_domain }}.{{ item.name | lower | regex_replace('[^a-z0-9]+', '-') }}.plist"
    mode: "0644"
  loop: "{{ autostart_apps }}"
  loop_control:
    label: "{{ item.name }}"
