---
wget -P "${ONESETUP_DIR:-/opt/onesetup}/roles/themes/files/bat" https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme

- name: "get latest catppuccin theme file from github"
  command: "curl -sL https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme"
  register: remote_content

- name: "get local file content"
  slurp:
    src: "{{ role_path }}/files/bat/catppuccin_mocha.tmTheme"
  register: local_content

- name: "compare local and remote theme file"
  assert:
    that:
      - remote_content.stdout | b64encode == local_content.content
    fail_msg: "theme needs update"
    success_msg: "theme is up-to-date"
