---
# Check for existing rustup binary
- name: "Check if rustup binary exists"
  ansible.builtin.stat:
    path: "{{ CARGO_HOME }}/bin/rustup"
  register: rustup_bin
  become: false

# Check for existing rustup toolchain
- name: "Check if rustup toolchains exist"
  ansible.builtin.find:
    paths: "{{ RUSTUP_HOME }}/toolchains"
    file_type: any
  register: rustup_toolchains
  become: false
  ignore_errors: true # path may not exist yet

# Ensure gcc is installed on Linux Systems (dependency of rustup)
- name: "Ensure gcc is installed for rustup to work"
  ansible.builtin.package:
    name: gcc
    state: present
  become: true
  when: ONESETUP_SYSTEM_OS == 'linux'

# Install Rustup if previous checks detected no rust installation via rustup
- name: "Install & Initialize rustup"
  # NOTE: The Cargo Environment has to be sourced in the shell config files as we install with '--no-modify-path'
  ansible.builtin.shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
  args:
    executable: "{{ bash_path | default('/bin/bash', true) }}"
  environment:
    CARGO_HOME: "{{ CARGO_HOME }}"
    RUSTUP_HOME: "{{ RUSTUP_HOME }}"
  become: false
  when:
    - not rustup_bin.stat.exists
    - (rustup_toolchains.matched | default(0)) == 0
