---
# Clone Dotfiles Repository
- name: "Clone Dotfiles Repository"
  ansible.builtin.git:
    repo: "{{ ONESETUP_DOTFILES_REPO_URI }}"
    clone: true
    dest: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}"
    force: false # respect local changes to prevent dotfile loss
    remote: origin
    update: true
    recursive: true # whether submodules should be included/skipped
  become: false
  register: dotfiles_clone
  failed_when: false # suppresses possible error message as this is handled down below
  # ignore_errors: true

# Prompt User if local changes can be overwritten
- name: "Prompt: Overwrite Local Dotfiles Directory?"
  ansible.builtin.pause:
    prompt: "Local modifications detected in {{ ONESETUP_SYSTEM_DOTFILES_DIR }}. Overwrite and lose local changes? [y/n]"
  register: dotfiles_overwrite_prompt
  when: dotfiles_clone is failed

# Clone Dotfiles Repository and force overwrite local changes (after user confirmation)
- name: "Clone Dotfiles Repository (force overwrite)"
  ansible.builtin.git:
    repo: "{{ ONESETUP_DOTFILES_REPO_URI }}"
    clone: true
    dest: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}"
    force: true # overwrite local changes as the user confirmed this
    remote: origin
    update: true
    recursive: true # whether submodules should be included/skipped
  become: false
  when:
    - dotfiles_clone is failed
    - dotfiles_overwrite_prompt.user_input | lower == 'y'

# Notify: Skipping Dotfiles Rollout
- name: "Info: Skipping Dotfiles Rollout.."
  ansible.builtin.debug:
    msg: "Skipping Dotfiles Rollout & continue playbook — local changes in {{ ONESETUP_SYSTEM_DOTFILES_DIR }} preserved."
  when:
    - dotfiles_clone is failed
    - dotfiles_overwrite_prompt.user_input | lower != 'y'

# Skip Dotfiles Role and continue playbook if User declined to overwrite local changes
- name: "Skip Dotfiles Role and continue playbook"
  meta: end_role
  when:
    - dotfiles_clone is failed
    - dotfiles_overwrite_prompt.user_input | lower != 'y'

# Find Global Shell Files
- name: "Find global shell files (top-level)"
  ansible.builtin.find:
    paths: "{{ shell_global.src }}"
    file_type: file
    recurse: true
  register: global_shell_files

# Copy: Global Shell Files
- name: "Copy global shell files to /etc"
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ shell_global.dest }}/{{ item.path | relpath(shell_global.src) }}"
    mode: "0644"
    owner: "root"
    group: "wheel"
    force: true
    remote_src: true
  loop: "{{ global_shell_files.files }}"
  become: true

# # Copy: Global Shell Files
# - name: "Copy global shell files to /etc"
#   ansible.builtin.copy:
#     src: "{{ item.path }}"
#     dest: "{{ shell_global.dest }}/{{ item.path | basename }}"
#     mode: "0644"
#     owner: "root"
#     group: "wheel"
#     force: true
#     remote_src: true
#   loop: "{{ global_shell_files.files }}"
#   become: true

# Copy: Global paths.d directory
# - name: "Copy paths.d directory to /etc/paths.d"
#   ansible.builtin.copy:
#     src: "{{ shell_global.src }}/paths.d/"
#     dest: "{{ shell_global.dest }}/paths.d/"
#     mode: "0644"
#     owner: "root"
#     group: "wheel"
#     force: true
#     remote_src: true
#   become: true

# Cleanup: Shell Config Directory
- name: "Cleanup: Shell Config Directory"
  ansible.builtin.file:
    path: "{{ shell_config.dest }}"
    state: absent
    force: true

# Symlink: Shell Config Directory
- name: "Symlink shell config directory"
  ansible.builtin.file:
    src: "{{ shell_config.src }}"
    dest: "{{ shell_config.dest }}"
    state: link
    force: true

# Find: User Shell Files
- name: "Find: User Shell Files"
  ansible.builtin.find:
    paths: "{{ shell_home.src }}"
    file_type: file
    hidden: true # Important to include hidden files starting with '.'
  register: user_shell_files

# Symlink: User Shell Files
- name: "Symlink: User Shell Files"
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ shell_home.dest }}/{{ item.path | basename }}"
    state: link
    force: true
  loop: "{{ user_shell_files.files }}"

# Cleanup: Dotfiles (dest)
- name: "Cleanup: Dotfiles"
  ansible.builtin.file:
    path: "{{ item_dotfiles.dest }}"
    state: "absent"
    force: true
  loop: "{{ dotfiles }}"
  loop_control:
    loop_var: "item_dotfiles"
  ignore_errors: true
  become: true

# Symlink: Dotfiles
- name: "Symlink: Dotfiles"
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: "link"
    force: true
  loop: "{{ dotfiles }}"
  ignore_errors: true
