---
# Include OS-Independent Tasks for all Operating Systems
- name: "Include OS-Independent Tasks (all)"
  ansible.builtin.include_tasks:
    file: "{{ item_roletask }}"
    apply:
      tags: ["{{ role_name }}"]
  loop: "{{ (query('ansible.builtin.fileglob', role_tasks_dir ~ '/*.yml') | sort) if role_tasks_dir is directory else [] }}"
  loop_control:
    loop_var: item_roletask
    label: "{{ item_roletask | basename }}"
  vars:
    role_tasks_dir: "{{ role_path }}/tasks/all"

# Include OS-Specific Tasks
- name: "Include OS-Specific Tasks ({{ ONESETUP_SYSTEM_OS }})"
  ansible.builtin.include_tasks:
    file: "{{ item_roletask }}"
    apply:
      tags: ["{{ role_name }}"]
  loop: "{{ (query('ansible.builtin.fileglob', role_tasks_dir ~ '/*.yml') | sort) if role_tasks_dir is directory else [] }}"
  loop_control:
    loop_var: item_roletask
    label: "{{ item_roletask | basename }}"
  vars:
    role_tasks_dir: "{{ role_path }}/tasks/{{ ONESETUP_SYSTEM_OS }}"
