---
# display all available facts
- name: "Display all available facts"
  ansible.builtin.debug:
    var: ansible_facts
# check if ansible connect user has sudo privileges
- name: "Ensure Ansible Connect User has sudo privileges"
  block:
    - name: "Test sudo access"
      become: true
      command: "whoami"
      register: sudo_check
    - debug:
        msg: "✓ SUCCESS: User has sudo privileges (whoami returned: {{ sudo_check.stdout }})"
  rescue:
    - debug:
        msg: "✗ FAILED: User does not have sudo privileges"
