---
- name: "Group: Ensure 'wheel' exists"
  ansible.builtin.group:
    name: "wheel"
    state: present
    system: false
- name: "Group: Ensure 'staff' exists"
  ansible.builtin.group:
    name: "staff"
    state: present
    system: false
- name: "Group: Ensure 'service' exists"
  ansible.builtin.group:
    name: "service"
    state: present
    system: true

- name: "Configure User & default shell"
  user:
    name: "{{ ansible_user }}"
    comment: "{{ ansible_user }}"
    hidden: false
    group: "staff"
    append: true # true: add user to the specified group but don't remove him from existing groups.
    shell: "/opt/homebrew/bin/bash" # TODO: linux support
    password: "{{ sudo_password }}"
    update_password: "always" # update password if they differ [always/on_create]
