---
# Create Groups
- name: "Group: Ensure 'wheel' exists"
  ansible.builtin.group:
    name: "wheel"
    state: present
    system: false
- name: "Group: Ensure 'staff' exists"
  ansible.builtin.group:
    name: "staff"
    state: present
    system: false
- name: "Group: Ensure 'service' exists"
  ansible.builtin.group:
    name: "service"
    state: present
    system: true

# Verify Users & Groups
- name: "Ensure Ansible Connect User has sudo privileges"
  block:
    - name: "Test sudo access"
      become: true
      command: "whoami"
      register: sudo_check
    - debug:
        msg: "✓ SUCCESS: User has sudo privileges (whoami returned: {{ sudo_check.stdout }})"
  rescue:
    - debug:
        msg: "✗ FAILED: User does not have sudo privileges"

