---
autostart_domain: com.onesetup.autostart

autostart_apps:
  # Utilities
  - { name: AeroSpace, bundle_id: bobko.aerospace }
  - { name: Thaw, bundle_id: com.stonerl.Thaw }
  - { name: SuperCmd, bundle_id: com.supercmd.app }
  - { name: DockDoor, bundle_id: com.ethanbills.DockDoor }
  # GUI Apps
  - { name: kitty, bundle_id: net.kovidgoyal.kitty }
  - {
      name: Firefox Developer Edition,
      bundle_id: org.mozilla.firefoxdeveloperedition,
    }
  - { name: Spotify, bundle_id: com.spotify.client }
  - { name: KeePassXC, bundle_id: org.keepassxc.keepassxc }
  - { name: Microsoft Teams, bundle_id: com.microsoft.teams2 }
  - { name: Microsoft Outlook, bundle_id: com.microsoft.Outlook }
  - { name: Todoist, bundle_id: com.todoist.mac.Todoist }
  - { name: Obsidian, bundle_id: md.obsidian }
