---
autostart_domain: com.onesetup.autostart

autostart_apps:
  - { name: Kitty }
  - { name: Firefox Developer Edition }
  - { name: Spotify }
  - { name: KeePassXC }
  - { name: Microsoft Teams }
  - { name: Microsoft Outlook }
