---
# Include OS-Independent Tasks for all Operating Systems
- name: "Include OS-Independent Tasks for all Operating Systems"
  ansible.builtin.include_tasks: "{{ item_roletask }}"
  with_fileglob:
    - "{{ role_path }}/tasks/all/*.yml"
  loop_control:
    loop_var: item_roletask

# Include OS-Specific Tasks for `{{ ONESETUP_SYSTEM_OS }}`
- name: "Include OS-Specific Tasks for {{ ONESETUP_SYSTEM_OS }}"
  ansible.builtin.include_tasks: "{{ item_roletask }}"
  with_fileglob:
    - "{{ role_path }}/tasks/{{ ONESETUP_SYSTEM_OS }}/*.yml"
  loop_control:
    loop_var: item_roletask
