- name: "pyenv | install python 3.7"
  command:
    cmd: "pyenv install 3.7"
- name: "pyenv | install python 3.8"
  command:
    cmd: "pyenv install 3.8"
- name: "pyenv | install python 3.9"
  command:
    cmd: "pyenv install 3.9"
- name: "pyenv | install python 3.10"
  command:
    cmd: "pyenv install 3.10"
- name: "pyenv | install python 3.11"
  command:
    cmd: "pyenv install 3.11"
- name: "pyenv | install python 3.12"
  command:
    cmd: "pyenv install 3.12"
