---
# -- -- -- -- -- -- -- -- #
# --      GENERAL      -- #    
# -- -- -- -- -- -- -- -- #
# Measurement Units
- name: "set measurement units to centimeters"
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleMeasurementUnits
    type: string
    value: Centimeters
    state: present
# Automatic Software Updates
- name: "enable auto software updates"
  osx_defaults:
    domain: /Library/Preferences/com.apple.SoftwareUpdate
    key: AutomaticCheckEnabled
    type: int
    value: 1
  become: true
# Language
- name: "Set language to english(primary) and german(secondary)"
  osx_defaults:
    key: AppleLanguages
    type: array
    value:
      - en
      - de
# Dication Prompt
- name: "Disable dictation prompt"
  osx_defaults:
    domain: com.apple.HIToolbox
    key: AppleDictationAutoEnable
    type: int
    value: 0
# Window Opening Animation
- name: "Disable window opening animation"
  osx_defaults:
    domain: NSGlobalDomain
    # domain: "-g"
    key: NSAutomaticWindowAnimationsEnabled
    type: bool
    value: false

# -- -- -- -- -- -- -- -- #
# --      APPSTORE     -- #    
# -- -- -- -- -- -- -- -- #
# Automatic Updates
- name: "appstore | enable automatic updates"
  osx_defaults:
    domain: com.apple.commerce
    key: AutoUpdate
    type: bool
    value: true
# Automatic Downloads
- name: "appstore | enable automatic downloads"
  osx_defaults:
    domain: com.apple.commerce
    key: AutoUpdateRestartRequired
    type: bool
    value: true

# -- -- -- -- -- -- -- -- #
# --   USER INTERFACE  -- #    
# -- -- -- -- -- -- -- -- #
# Highlight Color
- name: "set highlight color"
  osx_defaults:
    key: AppleHighlightColor
    type: string
    value: "0.952900 0.545100 0.658800"
  notify: restart_systemui_server
# Accent Color
- name: "set accent color"
  osx_defaults:
    key: AppleAccentColor
    type: int
    value: 1
  notify: restart_systemui_server
# Scrollbars
- name: "always show scrollbars"
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowScrollBars
    type: string
    value: Always

# -- -- -- -- -- -- -- #
# --      DOCK      -- #    
# -- -- -- -- -- -- -- #
# Dock Position
- name: "dock | position"
  osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: bottom
  notify: restart_dock
# Dock Size
- name: "dock | size"
  osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: 50
  notify: restart_dock
# Dock Recent Apps
- name: "dock | show recents"
  osx_defaults:
    domain: com.apple.dock
    key: show-recents
    type: bool
    value: false
  notify: restart_dock
# Dock Autohide
- name: "dock | autohide"
  osx_defaults:
    domain: com.apple.dock
    key: show-autohide
    type: bool
    value: true
  notify: restart_dock
# Dock Autohide Animation
- name: "dock | hide animation"
  osx_defaults:
    domain: com.apple.dock
    key: mineffect
    type: string
    value: suck
  notify: restart_dock
# Dock Autohide Animation Duration
- name: "dock | autohide animation duration"
  osx_defaults:
    domain: com.apple.dock
    key: autohide-time-modifier
    type: float
    value: 0.7
  notify: restart_dock
# Dock Autohide Animation Delay
- name: "dock | autohide delay"
  osx_defaults:
    domain: com.apple.dock
    key: autohide-delay
    type: float
    value: 0
  notify: restart_dock
# Dock Pinned Apps
- name: "dock | show pinned apps"
  osx_defaults:
    domain: com.apple.dock
    key: static-only
    type: bool
    value: false
  notify: restart_dock
# Dock Show Spaces
- name: "dock | show spaces when scrolling up on a dock item"
  osx_defaults:
    domain: com.apple.dock
    key: scroll-to-open
    type: bool
    value: true
  notify: restart_dock
# Dock Spring Loading
- name: "dock | enable spring loading"
  osx_defaults:
    domain: com.apple.dock
    key: enable-spring-load-actions-on-all-items
    type: bool
    value: true
  notify: restart_dock

# -- -- -- -- -- -- -- #
# --    FINDER      -- #    
# -- -- -- -- -- -- -- #
# Show Quit Option
- name: "finder | show quit option"
  osx_defaults:
    domain: com.apple.finder
    key: QuitMenuItem
    type: bool
    value: false
  notify: restart_finder
# Show Extensions
- name: "finder | show extensions"
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
  notify: restart_finder
# Show Hidden Files
- name: "finder | show hidden files"
  osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
  notify: restart_finder
# Show Path Bar
- name: "finder | show path bar"
  osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true
  notify: restart_finder
# View Style
- name: "finder | view style"
  osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: Nlsv # list: Nlsv | colum: clmv | gallery: glyv | icon: icnv
  notify: restart_finder
# Folder Sorting
- name: "finder | keep folders on top"
  osx_defaults:
    domain: com.apple.finder
    key: _FXSortFoldersFirst
    type: bool
    value: true
  notify: restart_finder
# Search Scope
- name: "finder | search scope"
  osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: SCcf # SCcf = current folder | SCsp = previous scope | SCev = entire volume
  notify: restart_finder
# Bin Emptying
- name: "finder | empty bin after 30days"
  osx_defaults:
    domain: com.apple.finder
    key: FXRemoveOldTrashItems
    type: bool
    value: true
  notify: restart_finder
# Change File Extension Warning
- name: "finder | change file extension warning"
  osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false
  notify: restart_finder
# Save to iCloud
- name: "finder | save to icloud by default"
  osx_defaults:
    domain: com.apple.finder
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false
  notify: restart_finder
# Titlebar Hover Delay
- name: "finder | titlebar hover delay"
  osx_defaults:
    domain: NSGlobalDomain
    key: NSToolbarTitleViewRolloverDelay
    type: float
    value: 0
  notify: restart_finder
# Sidebar Icon Size
- name: "finder | sidebar icon size"
  osx_defaults:
    domain: NSGlobalDomain
    key: NSTableViewDefaultSizeMode
    type: int
    value: 2 # 1: small | 2: medium | 3: large
  notify: restart_finder

# -- -- -- -- -- -- -- -- #
# --      DESKTOP      -- #    
# -- -- -- -- -- -- -- -- #
# Keep Folders on top
- name: "desktop | keep folders on top"
  osx_defaults:
    domain: com.apple.finder
    key: _FXSortFoldersFirstOnDesktop
    type: bool
    value: true
  notify: restart_finder
# Show Desktop Items
- name: "desktop | show desktop items"
  osx_defaults:
    domain: com.apple.finder
    key: CreateDesktop
    type: bool
    value: false
  notify: restart_finder
# Show Volumes
- name: "desktop | show volumes"
  osx_defaults:
    domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    type: bool
    value: false
  notify: restart_finder
# Show External Volumes
- name: "desktop | show external volumes"
  osx_defaults:
    domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: bool
    value: false
  notify: restart_finder
# Show Removable Volumes
- name: "desktop | show removable volumes"
  osx_defaults:
    domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    type: bool
    value: false
  notify: restart_finder
# Show Connected Servers
- name: "desktop | show connected servers"
  osx_defaults:
    domain: com.apple.finder
    key: ShowMountedServersOnDesktop
    type: bool
    value: false
  notify: restart_finder

# -- -- -- -- -- -- -- -- #
# --      MENUBAR      -- #    
# -- -- -- -- -- -- -- -- #
# Clock Seperator
- name: "menubar | blink clock separator"
  osx_defaults:
    domain: com.apple.menuextra.clock
    key: FlashDateSeparators
    type: bool
    value: false
  notify: restart_systemui_server
# Clock Date Format
- name: "menubar | clock date format"
  osx_defaults:
    domain: com.apple.menuextra.clock
    key: DateFormat
    type: string
    value: "EEE HH:mm"
  notify: restart_systemui_server

# -- -- -- -- -- -- -- -- #
# --       MOUSE       -- #    
# -- -- -- -- -- -- -- -- #
# Mouse Acceleration
- name: "mouse | acceleration"
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.linear
    type: bool
    value: true
# Mouse Speed
- name: "mouse | speed"
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.scaling
    type: float
    value: 2

# -- -- -- -- -- -- -- -- #
# --      TERMINAL     -- #    
# -- -- -- -- -- -- -- -- #
# Terminal follow mouse focus
- name: "terminal | focus follows mouse"
  osx_defaults:
    domain: com.apple.Terminal
    key: FocusFollowsMouse
    type: bool
    value: true

# -- -- -- -- -- -- -- -- #
# --     TRACKPAD      -- #    
# -- -- -- -- -- -- -- -- #
# Click weight
- name: "trackpad | click weight"
  osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: FirstClickThreshold
    type: int
    value: 0 # light: 0 | medium: 1 | firm: 2
# Dragging with drag lock
- name: "trackpad | dragging with drag lock"
  osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: DragLock
    type: int
    value: 0
# Dragging without drag lock
- name: "trackpad | dragging without drag lock"
  osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: Dragging
    type: int
    value: 0
# 3 Finger Drag
- name: "trackpad | 3 finger drag"
  osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: TrackpadThreeFingerDrag
    type: bool
    value: false

# -- -- -- -- -- -- -- -- #
# --     KEYBOARD      -- #    
# -- -- -- -- -- -- -- -- #
# Key Hold Behaviour
- name: "keyboard | key hold behaviour"
  osx_defaults:
    domain: NSGlobalDomain
    key: ApplePressAndHoldEnabled
    type: bool
    value: false
# fn Key Behaviour
- name: "keyboard | 🌐︎ key behaviour"
  osx_defaults:
    domain: com.apple.HIToolbox
    key: AppleFnUsageType
    type: int
    value: 0 # 0: do nothing | 1: change input source | 2: show emojis & symbols | 3: start dication
# Function keys behaviour
- name: "keyboard | function keys behaviour (f1 - f12)"
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.keyboard.fnState
    type: bool
    value: true # true: use function keys as standard function keys | false: use function keys as media keys
# Drag on Gesture
- name: "keyboard | drag on gesture"
  osx_defaults:
    domain: NSGlobalDomain
    key: NSWindowShouldDragOnGesture
    type: string
    value: "YES"

# -- -- -- -- -- -- -- -- #
# --  MISSION CONTROL  -- #    
# -- -- -- -- -- -- -- -- #
# Rearrange Spaces
- name: "mission control | auto rearrange spaces based on recent use"
  osx_defaults:
    domain: com.apple.dock
    key: mru-spaces
    type: bool
    value: false
  notify: restart_dock
# Group Windows by application
- name: "mission control | group windows by application"
  osx_defaults:
    domain: com.apple.dock
    key: expose-group-apps
    type: bool
    value: true
  notify: restart_dock
# Switch to space with open windows
- name: "mission control | switch to space with open windows"
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleSpacesSwitchOnActivate
    type: bool
    value: true
# Seperate Spaces per display
- name: "mission control | seperate spaces per display"
  osx_defaults:
    domain: com.apple.spaces
    key: spans-display
    type: bool
    value: false
  notify: restart_dock

# -- -- -- -- -- -- -- -- -- #
# --   ACTIVITY MONITOR   -- #    
# -- -- -- -- -- -- -- -- -- #
# Update Frequency
- name: "activity monitor | update frequency"
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: UpdatePeriod
    type: int
    value: 3 # update frequency in seconds
# Activity Monitor Dock Icon
- name: "activity monitor | dock icon"
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: IconType
    type: int
    value: 0 # 0: default icon | 2: network usage | 3: disk usage | 5: cpu usage

# -- -- -- -- -- -- -- -- #
# --   MISCELLANEOUS   -- #    
# -- -- -- -- -- -- -- -- #
# Help Menu Position
- name: "help menu | position"
  osx_defaults:
    domain: com.apple.helpviewer
    key: DevMode
    type: bool
    value: false

# Apple Music Notification
- name: "dont show notification when a new song starts"
  osx_defaults:
    domain: com.apple.Music
    key: userWantsPlaybackNotifications
    type: bool
    value: false

# Application Quarantine Message
- name: "disable application quarantine message"
  osx_defaults:
    domain: com.apple.LaunchServices
    key: LSQuarantine
    type: bool
    value: false

# Auto Save
- name: "enable auto save"
  osx_defaults:
    domain: NSGlobalDomain
    key: NSCloseAlwaysConfirmsChanges
    type: bool
    value: true

# Time Machine
- name: "time machine | dont prompt to use time machine for new disks"
  osx_defaults:
    domain: com.apple.TimeMachine
    key: DoNotOfferNewDisksForBackup
    type: bool
    value: true

# Messages (iMessage)
- name: "messages | subject field"
  osx_defaults:
    domain: com.apple.MobileSMS
    key: MMSShowSubject
    type: bool
    value: true

# Feedback Assistant
- name: "feedback assistant | autogather large files"
  osx_defaults:
    domain: com.apple.appleseed.FeedbackAssistant
    key: Autogather
    type: bool
    value: true

# Apple Crash Report
- name: "disable apple crash reports"
  osx_defaults:
    domain: com.apple.CrashReporter
    key: DialogType
    type: string
    value: none

# Simulator
- name: "simulator | screenshot location"
  osx_defaults:
    domain: com.apple.iphonesimulator
    key: ScreenShotSaveLocation
    type: string
    value: "{{ CLOUD_DIR }}/media/images/screenshots"

# Disable Startup Sound
- name: "Disable Startup Sound"
  ansible.builtin.command: "nvram StartupMute=%01"
  become: true
  changed_when: true

# Restart MacOS when it freezes
- name: "Automatically Restart on System Freeze"
  ansible.builtin.command: "systemsetup -setrestartfreeze on"
  become: true
  changed_when: true
