# Ensure Directory: CONFIG_DIR
- name: "Ensure Directory exists: {{ ONESETUP_SYSTEM_CONFIG_DIR }}"
  ansible.builtin.file:
    path: "{{ ONESETUP_SYSTEM_CONFIG_DIR }}"
    state: directory
    mode: "0744"
    owner: "{{ ONESETUP_SYSTEM_USERNAME }}"
    group: "{{ ONESETUP_SYSTEM_USER_GROUP }}"
    follow: true # follow symlink
  become: true

# Ensure Directory: INSTALL_DIR
- name: "Ensure Directory exists: {{ ONESETUP_SYSTEM_INSTALL_DIR }}"
  ansible.builtin.file:
    path: "{{ ONESETUP_SYSTEM_INSTALL_DIR }}"
    state: directory
    mode: "0755"
    owner: "{{ ONESETUP_SYSTEM_USERNAME }}"
    group: "{{ ONESETUP_SYSTEM_USER_GROUP }}"
    follow: true # follow symlink
  become: true

# Ensure Directory: STORAGE_DIR
- name: "Ensure Directory exists: {{ ONESETUP_SYSTEM_STORAGE_DIR }}"
  ansible.builtin.file:
    path: "{{ ONESETUP_SYSTEM_STORAGE_DIR }}"
    state: directory
    mode: "0755"
    owner: "{{ ONESETUP_SYSTEM_USERNAME }}"
    group: "{{ ONESETUP_SYSTEM_USER_GROUP }}"
    follow: true # follow symlink
  become: true

# Ensure Directory: DOTFILES_DIR
- name: "Ensure Directory exists: {{ ONESETUP_SYSTEM_DOTFILES_DIR }}"
  ansible.builtin.file:
    path: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}"
    state: directory
    mode: "0755"
    owner: "{{ ONESETUP_SYSTEM_USERNAME }}"
    group: "{{ ONESETUP_SYSTEM_USER_GROUP }}"
    follow: true # follow symlink
  become: true

# Ensure Directory: BIN_DIR
- name: "Ensure Directory exists: {{ ONESETUP_SYSTEM_BIN_DIR }}"
  ansible.builtin.file:
    path: "{{ ONESETUP_SYSTEM_BIN_DIR }}"
    state: directory
    mode: "0755"
    owner: "{{ ONESETUP_SYSTEM_ROOT_USER }}"
    group: "{{ ONESETUP_SYSTEM_ADMIN_GROUP }}"
    follow: true # follow symlink
  become: true

# Ensure Directory: TMP_DIR
- name: "Ensure Directory exists: {{ ONESETUP_SYSTEM_TMP_DIR }}"
  ansible.builtin.file:
    path: "{{ ONESETUP_SYSTEM_TMP_DIR }}"
    state: directory
    mode: "0755"
    owner: "{{ ONESETUP_SYSTEM_ROOT_USER }}"
    group: "{{ ONESETUP_SYSTEM_ADMIN_GROUP }}"
  become: true
