# Ensure Directory: XDG_CONFIG_HOME
- name: "Ensure Directory exists: {{ XDG_CONFIG_HOME }}"
  ansible.builtin.file:
    path: "{{ XDG_CONFIG_HOME }}"
    state: directory
    mode: "0755"
    owner: "{{ ONESETUP_SYSTEM_USERNAME }}"
    group: "{{ ONESETUP_SYSTEM_USER_GROUP }}"
  become: true

# Ensure Directory: XDG_DATA_HOME
- name: "Ensure Directory exists: {{ XDG_DATA_HOME }}"
  ansible.builtin.file:
    path: "{{ XDG_DATA_HOME }}"
    state: directory
    mode: "0755"
    owner: "{{ ONESETUP_SYSTEM_USERNAME }}"
    group: "{{ ONESETUP_SYSTEM_USER_GROUP }}"
  become: true

# Ensure Directory: XDG_STATE_HOME
- name: "Ensure Directory exists: {{ XDG_STATE_HOME }}"
  ansible.builtin.file:
    path: "{{ XDG_STATE_HOME }}"
    state: directory
    mode: "0755"
    owner: "{{ ONESETUP_SYSTEM_USERNAME }}"
    group: "{{ ONESETUP_SYSTEM_USER_GROUP }}"
  become: true

# Ensure Directory: XDG_CACHE_HOME
- name: "Ensure Directory exists: {{ XDG_CACHE_HOME }}"
  ansible.builtin.file:
    path: "{{ XDG_CACHE_HOME }}"
    state: directory
    mode: "0755"
    owner: "{{ ONESETUP_SYSTEM_USERNAME }}"
    group: "{{ ONESETUP_SYSTEM_USER_GROUP }}"
  become: true

# Ensure Directory: CONFIG_DIR
- name: "Ensure Directory exists: {{ ONESETUP_SYSTEM_CONFIG_DIR }}"
  ansible.builtin.file:
    path: "{{ ONESETUP_SYSTEM_CONFIG_DIR }}"
    state: directory
    mode: "0755"
    owner: "{{ ONESETUP_SYSTEM_USERNAME }}"
    group: "{{ ONESETUP_SYSTEM_USER_GROUP }}"
    follow: true # follow symlink
  become: true

# Ensure Directory: TARGET_DIR (Installation or Development Directory)
- name: "Ensure Directory exists: {{ ONESETUP_SYSTEM_TARGET_DIR }}"
  ansible.builtin.file:
    path: "{{ ONESETUP_SYSTEM_TARGET_DIR }}"
    state: directory
    mode: "0755"
    owner: "{{ ONESETUP_SYSTEM_USERNAME }}"
    group: "{{ ONESETUP_SYSTEM_USER_GROUP }}"
    follow: true # follow symlink
  become: true

# Ensure Directory: STORAGE_DIR
- name: "Ensure Directory exists: {{ ONESETUP_SYSTEM_STORAGE_DIR }}"
  ansible.builtin.file:
    path: "{{ ONESETUP_SYSTEM_STORAGE_DIR }}"
    state: directory
    mode: "0755"
    owner: "{{ ONESETUP_SYSTEM_USERNAME }}"
    group: "{{ ONESETUP_SYSTEM_USER_GROUP }}"
    follow: true # follow symlink
  become: true

# Ensure Directory: DOTFILES_DIR
- name: "Ensure Directory exists: {{ ONESETUP_SYSTEM_DOTFILES_DIR }}"
  ansible.builtin.file:
    path: "{{ ONESETUP_SYSTEM_DOTFILES_DIR }}"
    state: directory
    mode: "0755"
    owner: "{{ ONESETUP_SYSTEM_USERNAME }}"
    group: "{{ ONESETUP_SYSTEM_USER_GROUP }}"
    follow: true # follow symlink
  become: true

# Ensure Directory: BIN_DIR
- name: "Ensure Directory exists: {{ ONESETUP_SYSTEM_BIN_DIR }}"
  ansible.builtin.file:
    path: "{{ ONESETUP_SYSTEM_BIN_DIR }}"
    state: directory
    mode: "0755"
    owner: "{{ ONESETUP_SYSTEM_ROOT_USER }}"
    group: "{{ ONESETUP_SYSTEM_ADMIN_GROUP }}"
    follow: true # follow symlink
  become: true

# Ensure Directory: TMP_DIR
- name: "Ensure Directory exists: {{ ONESETUP_SYSTEM_TMP_DIR }}"
  ansible.builtin.file:
    path: "{{ ONESETUP_SYSTEM_TMP_DIR }}"
    state: directory
    mode: "1777"
    owner: "{{ ONESETUP_SYSTEM_ROOT_USER }}"
    group: "{{ ONESETUP_SYSTEM_ADMIN_GROUP }}"
  become: true
