# -- INCLUDE OS SPECIFIC TASKS -- #
- name: "include macos tasks"
  include_tasks: osx.yml
  when: ansible_facts['os_family'] == "Darwin"

- name: "include fedora tasks"
  include_tasks: fedora.yml
  when: ansible_facts['os_family'] == "RedHat"
